# Site settings
title: gianluca orlando
baseurl: ''
url: 'https://orlandopoliba.github.io/'
github_username: orlandopoliba

markdown: kramdown

# kramdown:
#   math_engine: katex

plugins:
  - jekyll-katex
  - jekyll-sitemap
